services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.6
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$DOCKERHOST:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FAKTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO, kafka.Producer.async.DefaultEventHandler=INFO, state.change.logger=INFO"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'